services:
  mongodb:
    image: mongo:latest
    container_name: insights-dashboard-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=insights_dashboard
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"] # Changed mongo -> mongosh
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 40s # Added initialization period

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=insights_dashboard
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
